{"mappings":"AAaoB,IAClBA,QAAQC,IAAI,uBAEJC,MAERF,QAAQC,IAAI,yB,CACZ,MAAOE,GACPH,QAAQC,IAAI,U,CAGdD,QAAQC,IAAI","sources":["src/js/01-try-catch.js"],"sourcesContent":["// Обработка ошибок с try...catch\n//  - Синтаксис\n//  - Какие ошибки ловит\n//    - ❌ ошибки парсинга (parsing errors)\n//    - ✅ ошибки выполнения (runtime errors)\n//  - Ловит только ошибки в синхронном коде\n//    - Как словить ошибку в асинхронном коде\n//  - Объект ошибки\n//    - name\n//    - message\n//    - stack\n//  - Блок catch без объекта ошибки\n\ntry {\n  console.log('Внутри try до myVar');\n\n  myVar;\n\n  console.log('Внутри try после myVar');\n} catch (error) {\n  console.log('Ошибка!');\n}\n\nconsole.log('После try...catch');\n"],"names":["console","log","myVar","error"],"version":3,"file":"01-try-catch.71855166.js.map"}